### ISSUE TITLE
Alpha Release 1/7/2020 14:00 MT Replacing Celery/Rabbit with Job Supervisor

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#2151]
Most of the code has been on master for some time. 

It's likely alpha will be broken for a bit.

Rollback:
- fnl6:
  - [ ] docker tag ae7cc6aa036e radiasoft/sirepo:alpha
- fnl1:
  - [ ] rename job_driver in db/000.yml
  - [ ] bash rsc.sh alpha sirepo
- fnl6: 
  - [ ] rm -rf /srv/sirepo/db/supervisor*

Pre-release:
- fnl1:
  - [x] add job-supervisor-alpha.sirepo.com to named
  - [x] bash update.sh prod named
  - [x] merge rsconf:sirepo into master
  - [x] run_no_rsc=1 bash run.sh
  - diff -r srv-tmp/host-old srv/host 
    + SIREPO_FEATURE_CONFIG_JOB=
    + SIREPO_MPI_CORES=<n>
    + SIREPO_SRDB_ROOT=/srv/sirepo/db
    + PYKERN_PKDEBUG_REDIRECT_LOGGING=1
    + PYKERN_PKDEBUG_WANT_PID_TIME=1
    - SIREPO_RUNNER_DOCKER_IMAGE
    - SIREPO_SERVER_DB_DIR
    - PYKERN_PKDEBUG_REDIRECT_LOGGING=True
    - PYKERN_PKDEBUG_WANT_PID_TIME=True  
- fnl1:
  -  [x] add job config to db/000.yml
   ```yaml
     sirepo:
        job_driver:
          docker:
           hosts: [ fnl6b.bivio.biz ]
           parallel:
             cores: 8
             gigabytes: 8
             slots_per_host: 4
           sequential:
             gigabytes: 2
             slots_per_host: 4
          modules: [ docker, sbatch ]
          sbatch:
            host: cori.nersc.gov
            host_key: "cori.nersc.gov,128.55.209.23 ssh-rsa [..SNIP...]"
            sirepo_cmd: /global/homes/n/nagler/.pyenv/versions/sirepo-CHANNEL/bin/sirepo
            srdb_root: "/global/cscratch1/sd/{sbatch_user}/sirepo-CHANNEL"
        mpi_cores: 8
        simulation_db:
          sbatch_display: cori.nersc.gov
   -- Only needed for alpha (share some of the above, too, after prod release)
        pkcli:
          job_supervisor:
            port: 7001
   ```
  - [x] fix lib.sh to look for agent hosts
  - [x] login alpha.sirepo.com
  - [x] open a few simulation windows (parallel and serial)

Release:
- [x] run_no_rsc=1 bash run.sh
- [x] diff -r srv-tmp/host-old srv/host 
- [x] bash update.sh alpha sirepo

Validate:
- [x] journalctl -f sirepo_job_supervisor
- [x] refresh simulation windows (should be no op=run in supervisor log)
- [x] change parameters to run serial simulations
- [x] start simulation on parallel simulations
- [x] Look at /srv/sirepo/db/supervisor-job

NERSC:
- cori:
   - [x] radia_run alpha nersc-sirepo-update

Post-release cleanup:
- fnl1:
  - [x] remove celery/rabbit from {db,secret}/000.yml
  - [x] bash rsc.sh alpha sirepo -- will uninstall celery_sirepo
- fnl6:
  - [x] remove rabbit and old certs:
  ```sh
  systemctl stop rabbitmq
  systemctl disable rabbitmq
  rm -rf /etc/systemd/system/rabbitmq* /srv/rabbitmq
  rm  -f /etc/nginx/conf.d/star_sirepo_com.*
  ```
