### ISSUE TITLE
Alpha Release 2020-12-07 21:08:29 UTC

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3179]
- Fix broken tests. #3178
- Fix #3181 - removed g_type param #3182
- Fix #3093. Allow user to select madx lattice to use in controls app. #3131
- Fix #1351. Add role for jupyterhublogin. #3184

**Comment by robnagler** [comment]
- [ ] Build jupyterhub
- [ ] Need github keys for sirepo.
- [ ] Shutdown jupyterhub and remove config.
- [ ] Move `jupyterhub:` to `sirepo_jupyterhub:`.

- [ ] Setup nginx redirect:

```yml
      nginx:
        redirects:
          - host_or_uri: https://<sirepo-server>/jupyter/$request_uri
            server_names:
              - <jupyter-server>
```

- [ ] Add sirepo config:

```yaml
      sirepo:
        auth:
          methods:
            - email
            - github
          github:
            key: <key>
            secret: <secret>
            method_visible: false
      feature_config:
        proprietary_sim_types:
          - jupyterhublogin
      sim_api:
        jupyterhublogin:
           rs_jupyter_migrate: true
      sirepo_jupyterhub:
        pools:
           <setup pools>
```
