### ISSUE TITLE
jupyter beta release plan

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/sirepo#3210]
- [x] run bash remove-jupyterhub.sh beta
- [x] change update.sh to no longer call update_jupyter and instead do inline.

    Add nginx redirect:
```yaml
      nginx:
        redirects:
          - host_or_uri: https://<sirepo-server>/jupyter/$request_uri
            server_names:
              - <jupyter-server>
```
    Add sirepo config:
```yaml
      sirepo:
        auth:
          methods:
            - github
          github:
            # secrets elsewhere
            method_visible: false # except alpha
      feature_config:
        proprietary_sim_types:
          - jupyterhublogin
RENAME jupyterhub: to sirepo_jupyterhub:
```
