### ISSUE TITLE
jupyter prod release plan

### ISSUE THREAD

**Issue by robnagler** [radiasoft/sirepo#3223]
- [ ] bash remove-jupyterhub.sh prod

- [ ] Add nginx redirect:
```yaml
      nginx:
        redirects:
          - host_or_uri: https://<sirepo-server>/jupyter/$request_uri
            server_names:
              - <jupyter-server>
```
- [ ] Add sirepo config:
```yaml
      sirepo:
        auth:
          methods:
            - github
          github:
            # secrets elsewhere
            method_visible: false
      feature_config:
        proprietary_sim_types:
          - jupyterhublogin
RENAME jupyterhub: to sirepo_jupyterhub:
```

- [ ] bash update.sh prod sirepo
