### ISSUE TITLE
provide feedback when epics value changes

### ISSUE THREAD

**Issue by moellep** [radiasoft/sirepo#5685]
In the accel app, when a read-only values change and is updated in the UI, it would be nice if it highlighted the field briefly. 

For example, color the input background light green and fade out. The controls app did this by setting using this css:
```css
@keyframes sr-updated {
  0% {
    background: #dff0d8;
  }
  100% {
    background: none;
  }
}

.sr-updated-cell {
  animation: sr-updated 1.5s ease;
}
```
and turning that class on/off with a $timeout. 

For example, in the simscopy epics example, when the "Min Value" is updated, the field should flash green briefly.

This probably needs to be set via jquery, because the input element doesn't allow class overrides in the angular app. So, possibly something like this pseudocode (only more general).

```javascript
$(".model-MTEST-MinValue input").addClass('sr-updated');
$timeout(() => $(".model-MTEST-MinValue input").addClass('sr-updated'), 1500);
```
